# Generated by Django 2.2.4 on 2019-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlikler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etkinlik',
            name='resim2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
