# Generated by Django 2.2.4 on 2019-10-02 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=64)),
                ('icerik', models.TextField(blank=True)),
                ('icerik2', models.TextField(blank=True)),
                ('resim', models.ImageField(upload_to='')),
                ('resim2', models.ImageField(upload_to='')),
                ('tarih', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
